### ISSUE TITLE
Sources Change?

### ISSUE THREAD

**Issue by Technologx** [AnandChowdhary/saga-android#4]
How can I change the mp3 downloading website sources to my own?

**Comment by AnandChowdhary** [comment]
In the directory `saga-android/app/src/main/java/get/saga/MusicDownloader.java`, you'll see line 44:
```
String BASE_URL = "http://YouTubeInMP3.com/fetch/?video=http://www.youtube.com/watch?v=";
```
This is the URL that we use for downloading from the YouTube in MP3 web service. You can replace this URL and make your own API service that takes a video ID and returns the MP3 file. I don't recommend doing that since I cannot comment on its legality.

**Comment by Technologx** [comment]
What about downloading from a regular mp3 site?-------- Original Message --------Subject: Re: [AnandChowdhary/saga-android] Sources Change? (#4)From: Anand Chowdhary To: AnandChowdhary/saga-android CC: Technologx ,Author In the directory saga-android/app/src/main/java/get/saga/MusicDownloader.java, you'll see line 44:
String BASE_URL = "http://YouTubeInMP3.com/fetch/?video=http://www.youtube.com/watch?v=";

This is the URL that we use for downloading from the YouTube in MP3 web service. You can replace this URL and make your own API service that takes a video ID and returns the MP3 file. I don't recommend doing that since I cannot comment on its legality.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AnandChowdhary/saga-android","title":"AnandChowdhary/saga-android","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AnandChowdhary/saga-android"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AnandChowdhary in #4: In the directory `saga-android/app/src/main/java/get/saga/MusicDownloader.java`, you'll see line 44:\r\n```\r\nString BASE_URL = \"http://YouTubeInMP3.com/fetch/?video=http://www.youtube.com/watch?v=\";\r\n```\r\nThis is the URL that we use for downloading from the YouTube in MP3 web service. You can replace this URL and make your own API service that takes a video ID and returns the MP3 file. I don't recommend doing that since I cannot comment on its legality."}],"action":{"name":"View Issue","url":"https://github.com/AnandChowdhary/saga-android/issues/4#issuecomment-330026360"}}}

**Comment by AnandChowdhary** [comment]
Since Saga works with the YouTube API, you'll have to create your own API that takes the Video ID as a parameter and returns the MP3 file URL from whatever music downloading service you want to use.

**Comment by Technologx** [comment]
I have no idea how to do that. Thank you for the replies though.-------- Original Message --------Subject: Re: [AnandChowdhary/saga-android] Sources Change? (#4)From: Anand Chowdhary To: AnandChowdhary/saga-android CC: Technologx ,Author Since Saga works with the YouTube API, you'll have to create your own API that takes the Video ID as a parameter and returns the MP3 file URL from whatever music downloading service you want to use.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AnandChowdhary/saga-android","title":"AnandChowdhary/saga-android","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AnandChowdhary/saga-android"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AnandChowdhary in #4: Since Saga works with the YouTube API, you'll have to create your own API that takes the Video ID as a parameter and returns the MP3 file URL from whatever music downloading service you want to use."}],"action":{"name":"View Issue","url":"https://github.com/AnandChowdhary/saga-android/issues/4#issuecomment-330169303"}}}
